package webui

import (
	"embed"
	"io/fs"
	"net/http"
	"path"
	"strconv"
	"strings"
)

// dist is generated by `npm run build` in the web directory.
//
//go:embed dist
var distribution embed.FS

type handler struct {
	files      fs.FS
	fileServer http.Handler
	index      []byte
}

func Handler() http.Handler {
	files, err := fs.Sub(distribution, "dist")
	if err != nil {
		panic("open embedded web distribution: " + err.Error())
	}
	index, err := fs.ReadFile(files, "index.html")
	if err != nil {
		panic("read embedded web index: " + err.Error())
	}
	return &handler{
		files:      files,
		fileServer: http.FileServer(http.FS(files)),
		index:      index,
	}
}

func (h *handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	requestPath := path.Clean("/" + r.URL.Path)
	if requestPath == "/" {
		h.serveIndex(w, r)
		return
	}

	assetPath := strings.TrimPrefix(requestPath, "/")
	if info, err := fs.Stat(h.files, assetPath); err == nil && !info.IsDir() {
		if strings.HasPrefix(requestPath, "/assets/") {
			w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
		} else {
			w.Header().Set("Cache-Control", "public, max-age=3600")
		}
		h.fileServer.ServeHTTP(w, r)
		return
	}

	// Frontend routes without a file extension receive the SPA shell.
	if path.Ext(requestPath) == "" {
		h.serveIndex(w, r)
		return
	}

	http.NotFound(w, r)
}

func (h *handler) serveIndex(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Cache-Control", "no-store")
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("Content-Length", strconv.Itoa(len(h.index)))
	w.WriteHeader(http.StatusOK)
	if r.Method != http.MethodHead {
		_, _ = w.Write(h.index)
	}
}
