ALTER TABLE books ADD COLUMN summary TEXT NOT NULL DEFAULT '';
ALTER TABLE books ADD COLUMN writer TEXT NOT NULL DEFAULT '';
ALTER TABLE books ADD COLUMN publisher TEXT NOT NULL DEFAULT '';
ALTER TABLE books ADD COLUMN publication_year INTEGER;
ALTER TABLE books ADD COLUMN volume TEXT NOT NULL DEFAULT '';
ALTER TABLE books ADD COLUMN number TEXT NOT NULL DEFAULT '';
ALTER TABLE books ADD COLUMN language TEXT NOT NULL DEFAULT '';
